### ISSUE TITLE
Error when writing the headers in pyslow5

### ISSUE THREAD

**Issue by uaudith** [hasindu2008/slow5lib#78]
Hello, I got the error 'NoneType' object has no attribute 'encode' 

`python version: 3.11.2`
`pyslow5 version: 1.1.0`

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[13], line 8
      5 end_reason_labels = s5_input.get_aux_enum_labels('end_reason')
      6 headers = s5_input.get_all_headers(read_group=0)
----> 8 ret = s5_out.write_header(headers, read_group=0, end_reason_labels=end_reason_labels)
      9 print("ret: write_header(): {}".format(ret))
     11 for read in s5_input.reads_multi(threads=92, batchsize=4096, aux='all'):

File python/pyslow5.pyx:1692, in pyslow5.Open.write_header()

AttributeError: 'NoneType' object has no attribute 'encode' 
```

while running

```python
# open file
s5_input = pyslow5.Open('/home/shared/e17-g13-nanopore-compression/hg/hg2_prom_lsk114_subsubsample/reads.blow5','r')
s5_out = pyslow5.Open('/home/uaudith/fyp/fft/1.slow5','w')

end_reason_labels = s5_input.get_aux_enum_labels('end_reason')
headers = s5_input.get_all_headers(read_group=0)

ret = s5_out.write_header(headers, read_group=0, end_reason_labels=end_reason_labels)
print("ret: write_header(): {}".format(ret))

for read in s5_input.seq_reads_multi(threads=92, batchsize=4096, aux='all'):
    # sig = read['signal']
    # fs = read['sampling_rate']
    # read['signal'] = transform(sig, fs, 20)

    # get an empty record and aux dictionary
    record, aux = s5_out.get_empty_record(aux=True)
    for i in read:
        if i in record:
            record[i] = read[i]
        if i in aux:
            aux[i] = read[i]

    # write the record
    ret = s5_out.write_record(record, aux)
s5_out.close()
```

I was able to solve this by replacing the header writing part with the following
```python
s5_input = pyslow5.Open('/home/shared/e17-g13-nanopore-compression/hg/hg2_prom_lsk114_subsubsample/reads.blow5','r')
s5_out = pyslow5.Open('/home/uaudith/fyp/fft/1.slow5','w')

end_reason_labels = s5_input.get_aux_enum_labels('end_reason')
header_original = s5_input.get_all_headers(read_group=0)

header, end_reason_labels = s5_input.get_empty_header(aux=True)
header_original = s5_input.get_all_headers()

for i in header_original:
    if i in header:
        if header_original[i] is None:
            continue
        else:
            header[i] = header_original[i]

ret = s5_out.write_header(header, read_group=0, end_reason_labels=end_reason_labels)
```

With that, I am getting the following error message but does not crash
`06-Sep-23 19:51:43 - pyslow5 - [ERROR]: write_record: slow5_aux_set could not write aux value end_reason: 6`

After the script was completed, the compression method was shown as none. I tried again with setting `s5_out = pyslow5.Open('/home/uaudith/fyp/fft/1.slow5','w', rec_press="zlib", sig_press="svb-zd")` but did not succeed.
![image](https://github.com/hasindu2008/slow5lib/assets/53704054/0595e0bd-3c6d-42d3-9e5a-a475799810c9)

Your insights are very much appreciated.

**Comment by Psy-Fer** [comment]
Hey,

So the first error, where encode can't operate on None, I will look into that. Looks like an oversight in my testing for absent values.

For the 2nd issue, it looks like your enum labels are not matching up with your data. Nanopore changed this recently and it can be a bit confusing. Can you dump the enum table from your data? And compare to what you are writing to file in the header?

For the third issue, with compression, you are writing to a slow5 file. This is an ascii human readable format. It will not apply any compression, even if you give the values. Change your extension output to blow5 and your compression args will work.

Hope this helps

Cheers,
James

**Comment by uaudith** [comment]
Thank you for the quick reply.
How do I get the enum table? is it the `s5_input.get_aux_enum_labels('end_reason')`
which gives,
`['unknown', 'partial', 'mux_change', 'unblock_mux_change', 'data_service_unblock_mux_change', 'signal_positive', 'signal_negative']`

**Comment by Psy-Fer** [comment]
Yea so you can see the 2 different kinds if enum nanopore have going. The one with data_service_unblock_mux_change is the latest one. Older data will only have the 5 fields. Worse, is they store the enum value, so when they changed the order by putting a label in the middle instead of the end, it made a real mess of things lol.

So that error of trying to write an enum value of 6 is using the old enum labels rather than the new enum labels.

Does that make sense?

**Comment by Psy-Fer** [comment]
So when you get the headers, the second arg return has the old enum table. Update it with the latest one instead, and use that rather than the default provided by pyslow5.

The empty header commands are more of a help for the user. I wrote it that way instead of hard coding it into the api because ont do silly things like change field names, types, and values on a whim. Sorry this has caused a problem for yet another developer.

Let me know if you can get it working.

(also there is another issue that has some example code to do what I describe. Let me get that)

**Comment by Psy-Fer** [comment]
Have a look at the code here

https://github.com/hasindu2008/slow5lib/issues/70#issuecomment-1594094571

**Comment by uaudith** [comment]
Thank you. It makes sense. I will try and update here.

Also, could you suggest a method to achieve parallelism when we read from a blow5, perform some processing, and then write to a new file? My initial thought was to employ a queue to store the reads from the input file and process it using Python's multiprocessing module. Would this approach cause issues when multiple processes attempt to write to the output file using s5_out.write_record?

**Comment by Psy-Fer** [comment]
You can read and write with multithreading on the slow5lib C side of pyslow5 with the seq_reads_multi() and write_record_batch() functions.

So reading from one big file and writing ti one big file, you have a similar setup to my buttery-eel basecalling wrapper.

The method I used there, was read the file and submit to an input queue using a single process. Spawn python processes to pull from the queue, and do stuff. Then I submit the output to an output queue. I then have a single process that pulls from the output queue, and writes to the output file.

So you can read and write with the single threaded method, or the multithreaded methods. Basically, the threading is used in the decompression/compression steps.

Alternatively, you can split your files, and read many/write many and let a process handle each file.

Do not have multiple processes write to the same file. That will not go well. It was bot designed to do that.

Given we can write zstd blow5 files ~2x faster than pod5 files, I think you should have pretty good performance. Have a look at blue-crab in my repos for that pattern.

Hope that helps. Of course let me know if you want some boiler plate code, but buttery-eel and blue-crab should have what you need.

Cheers
James

**Comment by Psy-Fer** [comment]
Specifically the multiproc branch of buttery-eel, these lines here

https://github.com/Psy-Fer/buttery-eel/blob/multiproc/src/buttery_eel.py#L691-L711

then you can see how I handle the queues and such in the functions.

**Comment by uaudith** [comment]
Correct me if I am wrong, but although the reading itself is multi-process, the next processing or transformation step is a single process. which can be a bottleneck if we are doing CPU-bound operations. So what I think is one process to put the reads into a queue and a set of processes (a pool) to process them and put them back into another queue. And another single process to write_record_batch().

**Comment by uaudith** [comment]
Thank you for the links. Looks like my use case is pretty similar to what you shared
