### ISSUE TITLE
Big endian support

### ISSUE THREAD

**Issue by hdeller** [hasindu2008/slow5lib#88]
I'm aware, that slow5lib currently does not support big-endian machines.
Nevertheless, when compiling on a big-endian machine (specifically: Linux on HP-PARISC), I get this error: 

: slow5_open_with::ERROR: Big endian machine detected. slow5lib only supports little endian at this time. Please open a github issue stating your machine spec <https://github.com/hasindu2008/slow5lib/issues>.

So, here is the bug report!
Full build log is here:
https://buildd.debian.org/status/fetch.php?pkg=libslow5lib&arch=hppa&ver=0.7.0%2Bdfsg-2.1&stamp=1713388301&raw=0

I'm happy to provide access to such a machine for you to test yourself! Just let me know!

Helge

**Comment by hasindu2008** [comment]
Never thought one would ever come to this error haha.
I am quite pleasantly surprised.

I would be happy to do the development to support big-endian. 

Would you happen to know of a system that I can get off the shelf for this dev?
Some online access to such a system is also adequate.

**Comment by Psy-Fer** [comment]
Oh wow i remember when we talked about this. And I was like, "nah, just chuck in a big warning. Anyone using a Big Endian is going to know what they are doing enough to come and talk to us about it"

**Comment by hdeller** [comment]
I'm actually very positively impressed by your answer and your willingness to look into it :-) That's not the case for many other projects...
Can you please send me a private email to deller@gmx.de with your preferred linux login name and your public ssh key, then I can send you the ssh login information to such a machine.
In case you have a debian developer key, you could log in to any of the existing porter machines (e.g. fast s390x or ppc64 machines) -> https://db.debian.org/machines.cgi?sortby=purpose&sortorder=dsc

**Comment by Koeng101** [comment]
@hdeller are you packaging slow5lib for Debian, so are testing on all the Debian systems?

**Comment by hdeller** [comment]
According to https://packages.debian.org/source/sid/libslow5lib the "Debian Med Packaging Team" and Andreas Tille maintain the slow5lib package on debian.
You can see the build results and logs for the various platforms here:
https://buildd.debian.org/status/package.php?p=libslow5lib&suite=sid

**Comment by hasindu2008** [comment]
Bigendian support is now tested and available in the latest slow5lib release https://github.com/hasindu2008/slow5lib/releases/tag/v1.2.0
